In [69]:
def function(n):
    import numpy as np
    mas = np.zeros((n,n+1))
    for i in range(n):
        if(i != 0):
            mas[i,i-1] = int(input("a"))
        mas[i,i] = int(input("b"))
        if(i != n-1):
            mas[i,i+1] = int(input("c"))
        mas[i,n] = int(input("r"))
    print(mas)    
    for i in range(n - 1):
        mas[i+1, 0:] = mas[i+1, 0:] - mas[i,0:]/mas[i,i]*mas[i+1,i]
    
    for j in range(n-1, 0, -1):
        mas[j-1,0:] = mas[j-1,0:] - mas[j,0:]*mas[j-1,j]/mas[j,j]
    for x in range(n):
        print(mas[x,n]/mas[x,x])
    
    
function(3)

b1
c2
r3
a4
b5
c6
r7
a8
b9
r10
[[ 1.  2.  0.  3.]
 [ 4.  5.  6.  7.]
 [ 0.  8.  9. 10.]]
0.19999999999999973
1.4000000000000001
-0.13333333333333336
