In [6]:
import numpy as np
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [10]:
a[0] = 2
a[9] = 5
c = a[0]
a[0] = a[len(a) - 1]
a[len(a) - 1] = c
print(a)

[5. 0. 0. 0. 1. 0. 0. 0. 0. 2.]


In [16]:
m = np.arange(9)
m = m.reshape(3,3)
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [44]:
k = np.random.random((10,2))
print(k)
r = k[:,0]*k[:,0] + k[:,1]*k[:,1]
f = np.arctan(k[:,1]/k[:,0])
print(r)
print(f)


[[0.18355683 0.88954943]
 [0.62559081 0.87817362]
 [0.57921109 0.29405719]
 [0.03441759 0.20926723]
 [0.86740317 0.51854432]
 [0.6257062  0.45544119]
 [0.15864762 0.50624454]
 [0.87271337 0.62682302]
 [0.91892255 0.41662385]
 [0.43206943 0.62941374]]
[0.82499129 1.16255277 0.42195511 0.04497734 1.02127648 0.59893492
 0.2814526  1.15453573 1.01799408 0.58284565]
[1.36730435 0.95181177 0.46977725 1.40778846 0.53880938 0.62919562
 1.26710867 0.62286703 0.42566366 0.9692133 ]
