In [1]:
import numpy as np
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [2]:
a[0] = 2
a[9] = 5
c = a[0]
a[0] = a[len(a) - 1]
a[len(a) - 1] = c
print(a)

[5. 0. 0. 0. 1. 0. 0. 0. 0. 2.]


In [3]:
m = np.arange(9)
m = m.reshape(3,3)
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
n = np.arange(64)
n = n.reshape(8,8)
for i in range(8):
    for j in range(8):
        n[i,j] = (i + j)%2
print(n)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [6]:

k = np.random.random((10,2))
print(k)
r = ( k[:,0]*k[:,0] + k[:,1]*k[:,1])**0.5
f = np.arctan(k[:,1]/k[:,0])
print(r)
print(f)

[[0.70444551 0.98040053]
 [0.83660519 0.99329385]
 [0.3788338  0.71218372]
 [0.59229369 0.71059354]
 [0.99044052 0.56730084]
 [0.54130944 0.00919355]
 [0.64669687 0.09984206]
 [0.94624895 0.16408777]
 [0.44827431 0.94442669]
 [0.74376593 0.74478705]]
[1.20724011 1.2986689  0.80667261 0.92507026 1.14140381 0.54138751
 0.65435868 0.9603707  1.04541457 1.05256615]
[0.94774321 0.87081675 1.08193011 0.8759481  0.52016149 0.01698227
 0.15317834 0.1717012  1.12763171 0.78608414]
